#!/bin/bash

is_playback_stopped=true  
keep_running=true
declare -A custom_urls

play_audio() {
  local url=$1

  if ! $is_playback_stopped; then
    stop_playback
  fi

  mpv "$url" --no-video --really-quiet & disown
  keep_running=false
  echo "Playback Started."
}

stop_playback() {
  pkill -f "mpv"
  echo "Playback stopped."
  is_playback_stopped=true
}


exit_script() {
  echo "Goodbye!"
  exit 0
}

if [[ "$1" == "-s" ]]; then
  stop_playback
  show_options=false
  exit_script
fi

while $keep_running; do

  echo "Choose an option:"
  echo "1. Play lofi"
  echo "2. Play whiteNoise"
  echo "3. Play classical"
  echo "4. Play ratatouille"
  echo "5. Manage custom videos"
  echo "6. Stop current playback"
  echo "7. Quit"

  read -p "Enter your choice: " choice

  case "$choice" in
    1)
      play_audio "https://www.youtube.com/watch?v=jfKfPfyJRdk"
      ;;

    2)
      play_audio "https://www.youtube.com/watch?v=vLEek3I3wac"
      ;;

    3)
      play_audio "https://www.youtube.com/watch?v=38LMlhYiQzc"
      ;;

    4)
      play_audio "https://www.youtube.com/watch?v=3ozXFWpFYzg"
      ;;

    5)
      while true; do
        echo "Manage custom videos:"
        echo "1. Play custom video"
        echo "2. List saved videos"
        echo "3. Play saved video"
        echo "4. Back to main menu"

        read -p "Enter your choice: " custom_choice

        case "$custom_choice" in
          1)
            read -p "Enter YouTube URL: " url
            read -p "Enter custom name: " name
            play_audio "$url"
            custom_urls["$name"]="$url"
            ;;
          2)
            echo "Saved videos:"
            for key in "${!custom_urls[@]}"; do
              echo "$key: ${custom_urls[$key]}"
            done
            ;;
          3)
            read -p "Enter custom name to play: " name
            if [ -n "${custom_urls[$name]}" ]; then
              play_audio "${custom_urls[$name]}"
            else
              echo "Custom video not found."
            fi
            ;;
          4)
            break
            ;;
          *)
            echo "Invalid choice"
        esac
      done
      ;;

    6)
      stop_playback
      ;;

    7)
      keep_running=false
      exit_script
      ;;

    *)
      echo "Invalid choice"
      ;;
  esac
done
